SELECT room_type FROM PGP.room ;

DESCRIBE TABLE ROOM;

INSERT INTO ROOM (ROOM_TYPE) VALUES ('DELUX'), ('AC'),('NON_AC'), ('NON_DELUX'), ('NON_DELUX');
-- INSERT INTO ROOM (ROOM_TYPE) VALUES;
-- INSERT INTO ROOM (ROOM_TYPE) VALUES ;
-- INSERT INTO ROOM (ROOM_TYPE) VALUES;
-- INSERT INTO ROOM (ROOM_TYPE) VALUES ('AC');
-- INSERT INTO ROOM (ROOM_TYPE) VALUES ('NON_AC');

